model_name: CT_RATE_Official_Pleural_Effusion
execution_mode: external_runtime
runtime: runtime-medical
runner_path: /app/models/CT_RATE_Official_Pleural_Effusion/runner.py
inference_path: /app/AI_Models/Pulmonology/CT_RATE_Official_Pleural_Effusion/inference.py
model_path: /app/AI_Models/Pulmonology/CT_RATE_Official_Pleural_Effusion/checkpoint
meta:
  description: CT-RATE Pleural effusion classifier (official__pleural_effusion).
  modality: nii, nii.gz
  task: classification
