model_name: TotalSegmentator_MSK_CT
execution_mode: external_runtime
runtime: runtime-nnunet
runner_path: /app/models/TotalSegmentator_MSK_CT/runner.py
inference_path: /app/AI_Models/Orthopedics/TotalSegmentator_MSK_CT/inference.py
model_path: /app/AI_Models/Orthopedics/TotalSegmentator_MSK_CT/checkpoint
params:
  fast: false
meta:
  description: 3D CT model returning segmentation overlays and volume, voxel, and
    mean-HU measurements for 74 musculoskeletal structures.
  modality: nii.gz, nii
  task: segmentation, quantification
